### ISSUE TITLE
List issue tracker website link on package page

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#211]
Also would be nice: detect if a package has a Github repo, and include an explicit Github link

**Comment by pythonissam** [comment]
We are trying to contribute to this. After adding necessary changes, we tried to build a server locally, and being stuck with this error:

```plain
SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"snapshot\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}
```

What we did is:

* installed PostgreSQL on local
* Created a user `stackage` with same password as user's name
* Created a Stackage DB

Can you help us resolve this error? Thank you.

**Comment by snoyberg** [comment]
Sorry about that, the docs are out of date. You'll need to run the cron job to create and populate the database. Can you try `stack exec stackage-server-cron`? You'll need to `export PGSTRING=...` first.

**Comment by pythonissam** [comment]
We tried `stack exec stackage-server-cron`, but it requires credential...

**Comment by snoyberg** [comment]
You'd have to give it the credentials for your local server.

**Comment by pythonissam** [comment]
@snoyberg Hmm... then, can you think of anything about this error?

```
$ stack exec stackage-server-cron
stackage-server-cron: MissingFileError "/home/bm12/.aws/credentials"
```

**Comment by lehins** [comment]
@pythonissam This is how `amazonka` normally works: AWS credentials are extracted form the environment in a similar way that `aws-cli` does it: you can either place them in
  `$HOME/.aws/credentials` or set them as environment variables
`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

**Comment by psibi** [comment]
@lehins I think @pythonissam is trying to setup stackage server locally. Is that possible ?

**Comment by lehins** [comment]
@psibi I am not really sure, as I never dealt with stackage insides before, but by taking a quick look at the script: https://github.com/fpco/stackage-server/blob/master/src/Stackage/Database/Cron.hs#L78, one of the things it's trying to do is upload a snapshot.json file and hoogledb onto an S3 bucket with name `"haddock.stackage.org"`, which kinda needs AWS credentials ;)

I am just familiar with an error @pythonissam is getting, so I decided to comment with a way it can be solved.

**Comment by psibi** [comment]
@lehins Thanks for the explanation!

@pythonissam Running stackage-server locally seems slight problematic now: https://github.com/fpco/stackage-server/commit/d7a0371cd6d2efaaf7b7fb7f0aff6d4f43512ad6

I'm working on this to resolve this so that stackage-server can be built locally without any issues. I will submit a PR in a couple of days. But if you are curious to try, I have updated the README in my experimental branch: https://github.com/psibi/stackage-server/tree/local-installation

**Comment by psibi** [comment]
I have created a PR which will hopefully make installation of stackage-server locally easy:   https://github.com/fpco/stackage-server/pull/257

**Comment by develop7** [comment]
@psibi the PR has been merged, but the "missing file .aws/credentials" error is still there; was that intentional?

**Comment by lehins** [comment]
@develop7 stackage-server-cron has changed quite a bit since that PR has been merged. Unfortunately aws credentials file is required for the cron job due to amazonka, there is no way around it, since it relies heavily on S3.

What you can try is placing an empty file in `.aws/credentials` and running the cron job with `--do-not-upload` flag, which will only use AWS S3 for looking at haddock files, but will not try to upload any hoogle related files, which then will not rely on actual credentials being valid. (Another hacky way would be setting `AWS_` variables to bogus values.)

The point is that the requirement of credentials being present comes from amaznoka, not from stackage-server, despite that they might not be used (eg. `--do-not-upload` is passed)

**Comment by develop7** [comment]
@lehins empty `credentials` file was not enough, only bogus credentials and `--do-not-upload` did the job. Thank you for the tip.
