### ISSUE TITLE
Broken link to the first Hoogle search result

### ISSUE THREAD

**Issue by kseo** [fpco/stackage-server#215]
The link of the first Hoogle search result is broken

For example, try https://www.stackage.org/lts-7.12/hoogle?q=Typeable

The link to "module Data.Typeable" is file:///tmp/hoogle-lts-7.1231/Data-Typeable.html

**Comment by snoyberg** [comment]
@ndmitchell Does something like this ring a bell by any chance?

**Comment by snoyberg** [comment]
Oh, I misread this at first. It's _only_ that first link, which is a `module` link. The other links still work. It would appear this is not a regression from the recent Hoogle bump we made, but likely a bug that already existed.

**Comment by snoyberg** [comment]
OK, this should be fixed now, can you give it a shot to confirm?

**Comment by kseo** [comment]
It works fine now Thanks!

**Comment by snoyberg** [comment]
Thanks for confirming!

**Comment by kseo** [comment]
Reopen the issue as I still see the sample problem with other search keywords.

Try https://www.stackage.org/lts-7.12/hoogle?q=bytestring

**Comment by snoyberg** [comment]
OK, should be fixed now too.
